stages:
  - package
  # - build

server-package:
  stage: package
  script:
   - cnpm i
   - npm run build
   - docker build -t itcast/front-analytics-cmm .
   - docker-compose up -d
  tags:
   - centos-137

# build:
#   stage: build
#   script:
#    - docker-compose up -d
#   tags:
#    - centos-137