import {createAPI} from '@/utils/request'

export const getResumesList = data => createAPI('/recruits/resumes', 'get', data)
export const getInterviewsList = data => createAPI('/recruits/interviews', 'get', data)
export const getEmploysList = data => createAPI('/recruits/employs', 'get', data)
export const getTalentsList = data => createAPI('/recruits/talents', 'get', data)
export const getPositionsList = data => createAPI('/recruits/positions', 'get', data)
export const getEmployApprovalsList = data => createAPI('/recruits/employ-approvals', 'get', data)
export const addPosition = data => createAPI('/recruits/positions', 'post', data)
export const changePosition = data => createAPI(`/recruits/positions/${data.id}`, 'put', data)
export const sresumeDetails = data => createAPI(`/recruits/resumes/${data.id}`, 'get', data)
export const employApproval = data => createAPI(`/recruits/employ-approval/${data.id}`, 'post', data)
export const interview = data => createAPI(`/recruits/interview/${data.id}`, 'post', data)
export const giveUpOffer = data => createAPI(`/recruits/employ-reject/${data.id}`, 'post', data)
export const dowResume = data => createAPI(`/recruits/resumes/${data.id}/download`, 'post', data)
export const recommendedResume = data => createAPI(`/recruits/resumes/${data.id}/recommended`, 'post', data)
export const sendOffer = data => createAPI(`/recruits/send-offer/${data.id}`, 'post', data)
export const importecruit = data => createAPI(`/recruits/import`, 'post', data)
export const getMessages = data => createAPI(`/recruits/messages`, 'get', data)
export const clsRecruit = data => createAPI(`/recruits/positions/${data.id}/close`, 'post', data)
export const deleteRecruit = data => createAPI(`/recruits/positions/${data.id}`, 'delete', data)
